# Global simulation configuration settings
SIMULATION:
  startTime: "01.01.2026 04:45:41" # UTC time. TODO: Remove, and implement automatic detection of start time based on first TLE Epoch
  simulationDuration: 6 # hours TODO: Add functionality that raises a warning if the duration is far beyond the last TLE's epoch
  use_old_skf_data: false # Skip Skyfield simulation (used when you want to use the same SGP4 baseline to compare against multiple Basilisk runs)
  old_skf_data_timestamp: "20251216_110041" # Timestamp WITHOUT "_skf" at the end

# Plotting options
PLOTTING:
  show_plots: true
  save_plots: false
  bypass_sim_to_plot: false
  data_timestamp_to_plot: "20251216_084208" # Only plots this data if bypass_sim_to_plot == true
  plot_prev_sim: false # TODO: NOT IMPLEMENTED. Also, 'implement func that skips simulations if this is true

# Global satellite configuration
SATELLITES:
  satellite_param_path: shared_input_data/satellite_param/satellite_param.yaml
  leader_tle_series_path: shared_input_data/tle_files/HYPSO-1_tle_series.txt
  inplane_separation_ang: 10 # [deg]
  num_satellites: 2
  
# Skyfield specific settings
SKYFIELD:
  config_path: Bsk_Skf_Propagation_Comparison/configs/overrides/skyfield.yaml

# Basilisk specific settings
BASILISK:
  config_path: Bsk_Skf_Propagation_Comparison/configs/overrides/basilisk.yaml