# These configuration options are currently in configs/default.yaml
BASILISK_SIMULATION:
  deltaT:                     5 # Solver time step [seconds]
  integrator:                 "RKF78" # [RK4(Default), RKF45, RKF78]

  sphericalHarmonicsDegree:   4 # int

  useSphericalHarmonics:      true

  useMsisDrag:                true 
  useExponentialDensityDrag:  false

  useSRP:                     false

  useSun3rdBody:              false 
  useMoon3rdBody:             false

  override_skf_initial_state: false