# These configuration options are currently in configs/default.yaml
BASILISK_SIMULATION:
  deltaT: 5 # Solver time step [seconds]
  integrator: "RKF45" # [RK4(Default), RKF45, RKF78]
  sphericalHarmonicsDegree: 4 # int
  useSphericalHarmonics: true
  useExponentialDensityDrag: true
  useSRP: true
  useSun3rdBody: true 
  useMoon3rdBody: true
  override_skf_initial_state: false